#! /bin/sh
### BEGIN INIT INFO
# Provides:          ReMountVagrantFolders
# Required-Start:    vboxguest
# Required-Stop:
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Short-Description: Global Cloud post vagrant boot script
# Description:       There are a few things that don't happen if the vm is booted
#                    from virtualbox instead of "vagrant up". This script attempts
#                    to correct those things. Notably the mounting of the vbox shared folders.
### END INIT INFO

# Using the lsb functions to perform the operations.
. /lib/lsb/init-functions
# Process name ( For display )
NAME=ReMountVagrantFolders

case $1 in
    start|restart|force-reload)
	if ! [ -e /vagrant/Vagrantfile ]; then
		mount -t vboxsf -o uid=1000,gid=1000 vagrant /vagrant
		mount -t vboxsf -o uid=1000,gid=1000 wwwroot /wwwroot
	fi
	;;
    stop)
	;;
    status)
	exit 0
	;;
    *)
	echo "Usage: $0 {start|stop|status|restart|force-reload}" >&2
	exit 3
	;;
esac

exit 0
